### ISSUE TITLE
Collected static files don't belong in git

### ISSUE THREAD

**Issue by robvdl** [HarshRaj709/Student_Discussion_app#1]
Just something I noticed, it seems your collected static files are ending up in git.

Traditionally collecstatic runs either on the target host just after a deploy, or if you build packages or Docker images it gets run at the time those packages are built.

But checking in collected static files in git will lead to a lot of noise every time upstream packages change their static files.

So collectstatic is often misunderstood, you should collect into a folder that is git ignored, or in a completely arbitrary location like /var/www

**Comment by robvdl** [comment]
As long as I've been doing Django, people have traditionally got confused with STATIC_ROOT.

STATIC_ROOT is the directory static files collect *into*

If you want a global static folder rather than one per app, you want this instead:

```python
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/"),
]
```

Or use Path objects instead of os.path.join if you want.

STATICFILES_DIRS is any "additional static dirs to look at on top of the ones in each app". This is where people generally put global static files for their app.

And STATIC_ROOT again is for collecting *into* not collecting *from*.

**Comment by robvdl** [comment]
Also, because you're still running with `DEBUG=True` (See issue #2), it won't require collecting static files yet because in DEBUG mode Django automatically serves static files from each app including third party ones.

Running collectstatic is only something that is necessary if DEBUG=False, so in production setups. That is why collecting static files is often done just in time after a deployment or during package build time if you're releasing Docker images or something but that is a bit more advanced.

**Comment by HarshRaj709** [comment]
In pythonanywhere, Debug = True is set

**Comment by robvdl** [comment]
Running in production is a harder topic. But the main thing I just wanted to put out is DEBUG shouldn't be set to True in a production app on the Internet. It opens the application up to being hackable as attackers will try to hit pages with weird requests, that produce server errors and then from that information returned they can then get debugging data from the server which gives them insight into the application and how it works.

By default Django has a few things hardcoded in settings py such as `DEBUG` and `SECRET_KEY` which need to be made configurable before an application can be put onto the Internet safely.

In the modern world we use environment variables for those now. Also called "the 12 factor app", Google it if you get a chance.

The SECRET_KEY setting as well, it has in there a comment saying `# SECURITY WARNING: keep the secret key used in production secret!` and then the key starts with `'django-insecure`. This isn't very clear but it's meant to be a hint or warning by Django to say that key is insecure and shouldn't be used in production.

So the way people do this commonly is have environment variable such as :

```shell
DJANGO_DEBUG=True
DJANGO_SECRET_KEY=ajisdhfiuahsfiuhaodiufhsdfadsfsadf
```

I guess you set these environment variables somewhere in pythonanywhere. There has to be a place to do set environment variables.

And you can use a library like django-environ to load these in settings.py.

The minimum django-environ setup in settings.py would be:

```python
# settings.py
import environ

env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DJANGOP_SECRET_KEY=(str, ""),
)

DEBUG = env("DJANGO_DEBUG")

SECRET_KEY = env("DJANGO_SECRET_KEY")
```

You can also enable Github's secret scanner that will also tell you if there are any secret keys it found in git.

Once a secret key is in Git then that secret key is considered compromised because even if you remove it, it doesn't erase the history of it being there in the past. So normally a new key would be generated and the old key considered compromised.

**Comment by HarshRaj709** [comment]
Thanks for your Valuable guidance
