### ISSUE TITLE
Deployed with DEBUG=True and hardcoded SECRET_KEY is a disaster waiting to happen

### ISSUE THREAD

**Issue by robvdl** [HarshRaj709/Student_Discussion_app#2]
I've mentioned this before on LinkedIn. I'm not trying to be pushy, but this is an actual gaping security hole.

If I go to any URL that doesn't exist if DEBUG=True I get a page listing all the URLs and IF it crashes anywhere in your code that is even worse, it will reveal details about the server environment.

https://harshraj710.pythonanywhere.com/sdfgsdfg

Settings like SECRET_KEY which have clearly been commented as "don't use this insecure key" need to come from environment variables or a config file. But environment variables is more the thing today.

**Comment by HarshRaj709** [comment]
Thanks
